services:
  postgres:
    container_name: postgres
    image: postgres:latest
    secrets: ['POSTGRES_PW']
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
      - POSTGRES_PASSWORD_FILE='/run/secrets/STORAGE_PASSWORD'
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always

# the observability staff  
  aspire-dashboard:
    container_name: aspire-dashboard
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard
    ports:
      - "18888:18888"
      - "4317:18889"
