services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB={$PROJECT_DB}
      - POSTGRES_USER={$DB_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
 #   volumes:
 #     - .data:/var/lib/postgresql/data:"rw"
    secrets:
      - db_password

  authelia:
    container_name: authelia
    image: authelia/authelia
    expose:
      - 9091
    environment:
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE:/run/secrets/encryption_key
    volumes:
      - ./.configs/authelia:/config
      - .data/authelia:/var/data
    secrets:
      - db_password
      - encryption_key
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./.configs/nginx/:/etc/nginx/conf.d
      - ./wwwroot:/usr/share/nginx/html
      - .data/logs/:/var/log/nginx/:rw
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - nginx_cert
      - nginx_cert_key
      - dhparam
    depends_on:
      - authelia
        
  whoami:
    container_name: whoami
    image: docker.io/traefik/whoami
    expose:
      - 80
      
  blogapi:
    build:
      context: blogapi
      target: final
    expose:
      - 8080
      - 8082
secrets:
  db_password:
    file: ./.secrets/db_password
  encryption_key:
    file: ./.secrets/encryption_key
    
  nginx_cert:
    file: .secrets/nginx/nginx-selfsigned.crt
  nginx_cert_key:
    file: .secrets/nginx/nginx-selfsigned.key
  dhparam:
    file: .secrets/nginx/dhparam.pem
    