services:
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB={$PROJECT_DB}
      - POSTGRES_USER={$DB_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
 #   volumes:
 #     - .data:/var/lib/postgresql/data:"rw"
    secrets:
      - db_password

  authelia:
    image: authelia/authelia
    ports:
      - "9091:9091"
      - "9092:9092"
    environment:
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE:/run/secrets/encryption_key
    volumes:
      - ./.configs/authelia:/config
      - .data/authelia:/var/data
    secrets:
      - db_password
      - encryption_key
    depends_on:
      - postgres

  nginx:
    image: nginx
    volumes:
      - ./.configs/nginx/:/etc/nginx/conf.d
      - ./wwwroot:/usr/share/nginx/html
      - .data/logs/:/var/log/nginx/:rw
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - nginx_cert
      - nginx_cert_key
      - dhparam
    depends_on:
      - authelia

secrets:
  db_password:
    file: ./.secrets/db_password
  encryption_key:
    file: ./.secrets/encryption_key
    
  nginx_cert:
    file: .secrets/nginx/nginx-selfsigned.crt
  nginx_cert_key:
    file: .secrets/nginx/nginx-selfsigned.key
  dhparam:
    file: .secrets/nginx/dhparam.pem