services:
  nginx:
    image: nginx
    volumes:
      - ./.configs/nginx/:/etc/nginx/conf.d
      - ./wwwroot:/usr/share/nginx/html
      - .data/logs/:/var/log/nginx/:rw
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - nginx_cert
      - nginx_cert_key
      - dhparam

secrets:
  nginx_cert:
    file: .secrets/nginx/nginx-selfsigned.crt
  nginx_cert_key:
    file: .secrets/nginx/nginx-selfsigned.key
  dhparam:
    file: .secrets/nginx/dhparam.pem